### ISSUE TITLE
Vendoring lldap fails when trying to also vendor from app/Cargo.toml

### ISSUE THREAD

**Issue by kastl-ars** [openSUSE-Rust/obs-service-cargo#102]
I am preparing a package for [LLDAP](https://github.com/lldap/lldap). The backend itself builds fine, but when I try to wasm-pack the frontend it fails.

While debugging I tried to add a second cargo_vendor service or modify the existing one, to also take into account the `./app/Cargo.toml` file (in case only vendoring the main one leads to missing dependencies).

However, I could not get this to work.

- Adding two `cargotoml` parameters and disabling `update` did not work, probably because there is only one lock file
  - using `respect-lockfile` set to false also did not work
- Using two services leads to missing dependencies in the app, as it needs things from the main package.

I'll open an issue upstream for the build errors, as I think this might be unrelated to the dependencies.

So, general question:

- Could this work at all, with two Cargo.toml files but only one Cargo.lock file?
- Could this work with one Cargo.toml needing stuff from the "main package"?

Kind Regards
Johannes

https://build.opensuse.org/package/show/home:ojkastl_buildservice:Branch_network_ldap/lldap

**Comment by kastl-ars** [comment]
Thanks @Firstyear for the reply.

I currently have two packages, one with and one without the wasm-pack. This way I can test the package (without a GUI, but with a working LLDAP server according to my tests).

https://build.opensuse.org/package/show/home:ojkastl_buildservice:Branch_network_ldap/lldap
https://build.opensuse.org/package/show/home:ojkastl_buildservice:Branch_network_ldap/lldap-with-wasm-pack

**Comment by Firstyear** [comment]
So it looks like this is a workspace, so you only need to vendor in the root. That will get everything for the server and wasm parts.

The error that is in the build appears to be with a derive macro, not a missing crate. So the issue may be how it's getting built.

If you attempt the wasm-pack command on an opensuse system in isolation, does it work or fail?

**Comment by kastl-ars** [comment]
Regarding the wasm-pack, I will do some more testing and discuss with upstream.

Regarding the vendoring:

So, if a project uses a workspace, I only need the Cargo.toml in the root directory? How do I know if a workspace is used (before running the cargo service, which tells me).

Is this workspace the reason why the vendoring with both Cargo.toml files failed? (In case I ever need that again, I would like to know how to do that properly...)

**Comment by Firstyear** [comment]
I believe the answer is "look at the Cargo.toml". https://github.com/lldap/lldap/blob/main/Cargo.toml#L1

Additionally, cargo-vendor tells you:

```
2024-10-16T23:50:42.245419Z  INFO obs_service_cargo::utils: 🍿 Vendoring for src 'kanidm-1.4.0~dev~git99.8c8f723.tar.zst'
2024-10-16T23:50:42.320975Z  INFO obs_service_cargo::utils: 📚 Project uses a workspace!   <<-- HERE
2024-10-16T23:50:42.321240Z  INFO obs_service_cargo::vendor: ⏫ Updating dependencies before vendor
```

If a work space is used, you don't need to look at any other Cargo.toml. Since when the vendor runs, it combines and gets all deps for *everything* in the workspace, including the wasm project (`app` in LLDAP's case).

**Comment by kastl-ars** [comment]
Perfect, thanks William!
