### ISSUE TITLE
Extend testsuite to include all possible flags

### ISSUE THREAD

**Issue by msirringhaus** [openSUSE-Rust/obs-service-cargo#104]
Given that #103 wasn't noticed before a release, the testsuite should probably be extended to make sure all flags (or at least most common combinations of flags) are tested.

**Comment by uncomfyhalomacro** [comment]
hi @msirringhaus. yeah i apologise that i didn't notice. two weeks ago was kind of fun. now i am back so maybe i will structure a test suite... maybe soon.

**Comment by uncomfyhalomacro** [comment]
fixed in https://github.com/openSUSE-Rust/obs-service-cargo/commit/eca8c768930a842884ac6f613c21c3bfcb9d18d3
