### ISSUE TITLE
crates from cargo_vendor not including git submodules

### ISSUE THREAD

**Issue by photosheep** [openSUSE-Rust/obs-service-cargo#106]
Using `cargo_vendor` on the package `warp` pulls the `license` crate without including `license-list-data`, breaking the build.
Downloading `license` from crates.io results in `license-list-data` being included.

**Comment by uncomfyhalomacro** [comment]
> Using `cargo_vendor` on the package `warp` pulls the `license` crate without including `license-list-data`, breaking the build. Downloading `license` from crates.io results in `license-list-data` being included.

I think that's an issue with `license-list-data` crate. their offline feature flag is not working at all.

See how I fixed it with `rye`, another crate that uses `license-list-data` - https://build.opensuse.org/projects/devel:languages:python/packages/rye/files/rye.spec?expand=1

**Comment by uncomfyhalomacro** [comment]
but i will still investigate this, i might be wrong after all. however, how do you run `cargo vendor`? what flags did you include when you do regular vendor @photosheep ?

**Comment by uncomfyhalomacro** [comment]
Confirmed that it's a bug in license. I just checked there whole code and there is no `cfg` or whatsoever.
