### ISSUE TITLE
cargo_vendor compression property "zstd"

### ISSUE THREAD

**Issue by xpufx** [openSUSE-Rust/obs-service-cargo#116]
I have a single obs job that stopped working at some point due to cargo_vendor not accepting "zstd" as an allowed property for compression. It looks like only 'zst' is supported now. It might have been lost during transitioning from the opensuse repo. I have solved my sole issue easy enough but there might be other jobs out there depending on that usage and it should not be difficult to include zstd as an undocumented alias for backward compatibility.

![image](https://github.com/user-attachments/assets/faccb1ee-ff07-4f67-a7aa-ae27262a83df)

**Comment by uncomfyhalomacro** [comment]
Implementation is adopted now in https://github.com/openSUSE-Rust/obs-service-cargo/commits/master/

**Comment by xpufx** [comment]
Thank you.
